dramas = [{"Name": "Move to Heaven", "Year of release": "2021", "Aired Date": "May 14, 2021", "Aired On": " Friday",
           "Number of Episode": "10", "Network": "Netflix ", "Duration": "52 min.",
           "Content Rating": "18+ Restricted (violence & profanity) ",
           "Synopsis": "Han Geu Roo is an autistic 20-year-old. He works for his fatherâ€™s business â€œMove To Heaven,â€ a company that specializes in crime scene cleanup, where they also collect and arrange items left by deceased people, and deliver them to the bereaved family.",
           "Cast": "Lee Je Hoon, Tang Jun Sang, Hong Seung Hee, Jung Suk Yong, Jung Young Joo, Lee Moon Shik",
           "Genre": "Life,  Drama ",
           "Tags": "Uncle-Nephew Relationship, Autism, Death, Mourning, Tearjerker, Savant Syndrome, Life Lesson, Cleaning And Organizing, Autism Spectrum Disorder, Murder",
           "Rank": "#1", "Rating": "9.2"},
          {"Name": "Weak Hero Class 1", "Year of release": "2022", "Aired Date": "Nov 18, 2022",
           "Aired On": " Friday Duration: 40 min. Content Rating: 18+ Restricted (violence & profanity) ",
           "Number of Episode": "8", "Network": "None", "Duration": "40 min.",
           "Content Rating": "18+ Restricted (violence & profanity) ",
           "Synopsis": "Yeon Shi Eun is a model student who ranks at the top of his high school. Physically, Yeon Shi Eun appears weak, but by using his wits and psychology, he fights against the violence that takes place inside and outside of his school. ",
           "Cast": "Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim Su Gyeom, Lee Yeon, Shin Seung Ho",
           "Genre": "Action,  Youth,  Drama ",
           "Tags": "Violence, Friendship, Bromance, School Bullying, High School, Skilled Fighter, Adapted From A Webtoon, Fight, Gang, Smart Male Lead",
           "Rank": "#2", "Rating": "9.1"},
          {"Name": "Hospital Playlist Season 2", "Year of release": "2021", "Aired Date": "Jun 17, 2021 - Sep 16, 2021",
           "Aired On": " Thursday", "Number of Episode": "12", "Network": "Netflix,  tvN ", "Duration": "1 hr. 40 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Everyday is extraordinary for five doctors and their patients inside a hospital, where birth, death and everything in between coexist.",
           "Cast": "Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim Dae Myung, Jeon Mi Do, Shin Hyun Bin",
           "Genre": "Romance,  Life,  Drama,  Medical ",
           "Tags": "Multiple Mains, Band, Music, Multiple Couples, Comedy, Illness, Strong Female Lead, Bromance, Divorced Male Lead, Long Distance Relationship",
           "Rank": "#3", "Rating": "9.1"},
          {"Name": "Flower of Evil", "Year of release": "2020", "Aired Date": "Jul 29, 2020 - Sep 23, 2020",
           "Aired On": " Wednesday, Thursday", "Number of Episode": "16", "Network": "tvN ",
           "Duration": "1 hr. 10 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Although Baek Hee Sung is hiding a dark secret surrounding his true identity, he has established a happy family life and a successful career. He is a loving husband and doting father to his young daughter. But his perfect faÃ§ade begins to crumble when his wife, Cha Ji Won, a homicide detective, begins investigating a string of serial murders from 15 years ago. Ji Won notices changes in Hee Sungâ€™s behavior and begins to wonder if he could possibly be hiding something from her. ",
           "Cast": "Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo Hyun Woo, Nam Ki Ae, Son Jong Hak",
           "Genre": "Thriller,  Romance,  Crime,  Melodrama ",
           "Tags": "Deception, Family Secret, Mystery, Suspense, Hidden Personality, Antisocial Personality Disorder, Investigation, Smart Female Lead, Murder, Hidden Identity",
           "Rank": "#4", "Rating": "9.1"},
          {"Name": "Hospital Playlist", "Year of release": "2020", "Aired Date": "Mar 12, 2020 - May 28, 2020",
           "Aired On": " Thursday", "Number of Episode": "12", "Network": "Netflix,  tvN ", "Duration": "1 hr. 30 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "The stories of people going through their days are seemingly ordinary but actually special at the hospital, a place known as the microcosm of life, where someone is being born and someone's life meets its ending. The five doctors are long-time friends of 20 years who started their undergrad in 1999 in the same medical school and now are colleagues in the same hospital and have a band together.",
           "Cast": "Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim Dae Myung, Jeon Mi Do, Shin Hyun Bin",
           "Genre": "Romance,  Life,  Drama,  Medical ",
           "Tags": "Multiple Mains, Slow Romance, Multiple Couples, Friendship, Bromance, Heartfelt, Slight Romance, Strong Female Lead, Healing, Nice Male Lead",
           "Rank": "#5", "Rating": "9.1"},
          {"Name": "Alchemy of Souls", "Year of release": "2022", "Aired Date": "Jun 18, 2022 - Aug 28, 2022",
           "Aired On": " Saturday, Sunday", "Number of Episode": "20", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 20 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Set in a fictional country called Daeho that does not exist in history or on maps, it is about the love and growth of young mages as they overcome their twisted fates due to a forbidden magic spell known as the \"alchemy of souls\", which allows souls to switch bodies.",
           "Cast": "Lee Jae Wook, Jung So Min, Hwang Min Hyun, Shin Seung Ho, Yoo  Joon Sang, Oh Na Ra",
           "Genre": "Action,  Historical,  Romance,  Fantasy ",
           "Tags": "Transmigration, Master-Disciple Relationship, Multiple Mains, Hidden Identity, Supernatural, Magical Power, Body Swap, Elemental Power, Strong Female Lead, Fake Identity",
           "Rank": "#6", "Rating": "9.1"},
          {"Name": "Reply 1988", "Year of release": "2015", "Aired Date": "Nov  6, 2015 - Jan 16, 2016",
           "Aired On": " Friday, Saturday", "Number of Episode": "20", "Network": "tvN ", "Duration": "1 hr. 35 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Five childhood friends, who all live in the same Ssangmundong neighborhood of Seoul, lean on each other to survive their challenging teen years and set a path for their futures. Sung Deok Sun struggles for attention as the middle child in her poor family while also carrying the burden of her 999th ranking in school. Kim Jung Hwan only has a one-track mind for soccer, even after his family becomes rich overnight. Sung Sun Woo is the perfect student, student council president and a caring and dependable son in his family. Ryu Dong Ryong is a geek who knows more about girls and life than the rest of his friends, but his poor academic score prevents him from being able to go to college. Choi Taek is a genius baduk player who dropped out of school to go professional. As the group of friends gets into and out of mischief around the neighborhood, what experiences from these memorable times together will they carry with them into their future lives? ",
           "Cast": "Lee Hye Ri, Go Kyung Pyo, Ryu Joon Yeol, Park Bo Gum, Lee Dong Hwi, Sung Dong Il",
           "Genre": "Comedy,  Romance,  Life,  Youth ",
           "Tags": "Nostalgia, Multiple Couples, Poor Family, Love Triangle, Heartfelt, High School, Friendship, Mother-Son Relationship, Coming Of Age, Bromance",
           "Rank": "#7", "Rating": "9.1"},
          {"Name": "My Mister", "Year of release": "2018", "Aired Date": "Mar 21, 2018 - May 17, 2018",
           "Aired On": " Wednesday, Thursday", "Number of Episode": "16", "Network": "tvN ",
           "Duration": "1 hr. 17 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Park Dong Hoon is a middle-aged engineer who is married to attorney Kang Yoon Hee. However, his life is not that happy as he has two unemployed brothers, Sang Hoon and Gi Hoon, who rely on him. Moreover, his wife is secretly having an affair with CEO Do Joon Yeong, his current boss and college junior.",
           "Cast": "Lee Sun Kyun, IU, Park Ho San, Song Sae Byuk, Lee Ji Ah, Kim Young Min",
           "Genre": "Psychological,  Life,  Drama ",
           "Tags": "Nice Male Lead, Depression, Healing, Poor Female Lead, Strong Female Lead, Infidelity, Lying, Power Struggle, Deception, Grandma-Granddaughter Relationship",
           "Rank": "#8", "Rating": "9.0"},
          {"Name": "Under the Queen's Umbrella", "Year of release": "2022", "Aired Date": "Oct 15, 2022 - Dec  4, 2022",
           "Aired On": " Saturday, Sunday", "Number of Episode": "16", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 10 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Within the palace exist troublemaking princes who cause nothing but headaches for the royal family and are about to be turned into properÂ crown princes. Their mother, Im Hwa Ryeong,  is the wife of a great king. But instead of having an aura of elegance and grace, she is a prickly, sensitive, and hot-temperedÂ queen. Once more serene, she changed since people kept pushing her buttons.  SheÂ is a queen who sometimes abandons her pride andÂ is even known to swear!  Every day of her life is full of trials, but she withstands them all, for the sake of her children.",
           "Cast": "Kim Hye Soo, Kim Hae Sook, Choi Won Young, Kim Eui Sung, Moon Sang Min, Ok Ja Yeon",
           "Genre": "Historical,  Comedy,  Drama,  Political ",
           "Tags": "Motherhood, Mother-Son Relationship, Palace Setting, Black Comedy, Queen Female Lead, Joseon Dynasty, Royal Family, Royalty, Historical Fiction, Prince Supporting Character",
           "Rank": "#9", "Rating": "9.0"},
          {"Name": "Prison Playbook", "Year of release": "2017", "Aired Date": "Nov 22, 2017 - Jan 18, 2018",
           "Aired On": " Wednesday, Thursday", "Number of Episode": "16", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 32 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Kim Je Hyuk, a famous baseball player, is arrested after using excessive force while chasing a man trying to sexually assault his sister. Shockingly to him and the rest of the nation, he is sentenced to a year in prison. There, he meets his childhood friend and fellow baseball player, Lee Joon Ho, who gave up on baseball after a car accident, but now is a prison guard and one of Je Hyuk's biggest fans. The drama revolves around Je Hyuk's time in prison, as well as the prisoners he meets and events that take place there.",
           "Cast": "Park Hae Soo, Jung Kyung Ho, Krystal Jung, Im Hwa Young, Ye Soo Jung, Kim Kyung Nam",
           "Genre": "Comedy,  Crime,  Life,  Drama ",
           "Tags": "Life Lesson, Bromance, Wrongfully Accused, Strong Male Lead, Slight Romance, Character Development, Murder, Prison Setting, Black Comedy, Baseball",
           "Rank": "#10", "Rating": "9.0"},
          {"Name": "The Glory Part 2", "Year of release": "2023", "Aired Date": "Mar 10, 2023", "Aired On": " Friday",
           "Number of Episode": "8", "Network": "Netflix ", "Duration": "55 min.",
           "Content Rating": "18+ Restricted (violence & profanity) ",
           "Synopsis": "Moon Dong Eun's silent fury against those students that horrifically abused her during her high school years continues to burn inside of her. She meticulously executes her plan to inflict ultimate pain on her tormentors. Meanwhile, the sudden disappearance of Son Myeong Oh has gotten the attention of the police and his friends. Joo Yeo Jeong follows Moon Dong Eun and is willing to do anything she asks in her pursuit of revenge. Before Moon Dong Eun begins her final moves, she offers her nemesis Park Yeon Jin a chance to save herself if she turns in to the police, but Park Yeon Jin has her own plans to stop Moon Dong Eun. A violent and bloody game of nerves plays out between these rivals.",
           "Cast": "Song Hye Kyo, Lee Do Hyun, Im Ji Yeon, Yeom Hye Ran, Park Sung Hoon, Jung Sung Il",
           "Genre": "Thriller,  Drama,  Melodrama ",
           "Tags": "Revenge, Graphic Violence, Brief Nudity, Suspense, Strong Female Lead, Domestic Violence, Trauma, Family Abuse, Perpetrator-Victim Relationship, Nudity",
           "Rank": "#11", "Rating": "9.0"},
          {"Name": "Mr. Queen", "Year of release": "2020", "Aired Date": "Dec 12, 2020 - Feb 14, 2021",
           "Aired On": " Saturday, Sunday", "Number of Episode": "20", "Network": "tvN ", "Duration": "1 hr. 15 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Jang Bong Hwan is a South Korean chef who has risen up the ranks to cook for the countryâ€™s top politicians in the Blue Houseâ€™s presidential residences. After a serious accident, he finds himself in the body of the young queen, Kim So Yong, when whisked away to an era deep in Koreaâ€™s past.",
           "Cast": "Shin Hye Sun, Kim Jung Hyun, Bae Jong Ok, Kim Tae Woo, Jo Yun Hee, Seol In Ah",
           "Genre": "Historical,  Comedy,  Romance,  Fantasy ",
           "Tags": "Transmigration, Sassy Female Lead, Joseon Dynasty, Eccentric Female Lead, Calm Male Lead, Time Travel, Marriage Of Convenience, Smart Male Lead, Nice Male Lead, Gender Swap",
           "Rank": "#12", "Rating": "9.0"},
          {"Name": "Mother", "Year of release": "2018", "Aired Date": "Jan 24, 2018 - Mar 15, 2018",
           "Aired On": " Wednesday, Thursday", "Number of Episode": "16", "Network": "tvN ", "Duration": "1 hr. 3 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Realizing one of her students is being abused, school teacher and bird researcher Soo Jin impulsively kidnaps the girl and acts as a substitute mother in an attempt to take care of her.",
           "Cast": "Lee Bo Young, Heo Yool, Lee Hye Young, Go Sung Hee, Lee Jae Yoon, Go Bo Gyeol",
           "Genre": "Thriller,  Mystery,  Psychological,  Melodrama ",
           "Tags": "Mother-Daughter Relationship, Independent Female Lead, Smart Female Lead, Child Abuse, Adoption, Strong Female Lead, Suspense, Orphan Female Lead, Motherhood, Investigation",
           "Rank": "#13", "Rating": "9.0"},
          {"Name": "Dr. Romantic Season 3", "Year of release": "2023", "Aired Date": "Apr 28, 2023 - Jun 17, 2023",
           "Aired On": " Friday, Saturday", "Number of Episode": "16", "Network": "SBS ", "Duration": "1 hr. 10 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "At Doldam Hospital, Dr. Kim Sa Bu and his team are committed to saving lives. After three years, a state-of-the-art trauma centre is set to open, equipped with the latest in medical technology.",
           "Cast": "Han Seok Kyu, Lee Sung Kyung, Ahn Hyo Seop, Kim Joo Heon, So Ju Yeon, Jin Kyung",
           "Genre": "Romance,  Drama,  Medical ",
           "Tags": "Hospital Setting, Teamwork, Genius Male Lead, Surgeon Male Lead, Neurosurgeon Male Lead, Hospital Director Male Lead, Doctor Female Lead, Doctor Male Lead, Hardworking Male Lead, Hardworking Female Lead",
           "Rank": "#14", "Rating": "9.0"},
          {"Name": "Crash Landing on You", "Year of release": "2019", "Aired Date": "Dec 14, 2019 - Feb 16, 2020",
           "Aired On": " Sunday, Saturday", "Number of Episode": "16", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 25 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "After getting into a paragliding accident, South Korean heiress Yoon Se Ri crash lands in North Korea. There, she meets North Korean army officer Ri Jung Hyuk, who agrees to help her return to South Korea. Despite the tension between their countries, the two of them start falling for one another.",
           "Cast": "Hyun Bin, Son Ye Jin, Seo Ji Hye, Kim Jung Hyun, Yang Kyung Won, Lee Shin Young",
           "Genre": "Military,  Comedy,  Romance,  Political ",
           "Tags": "North And South Korea, Strong Male Lead, Rich Female Lead, Fate, Nice Male Lead, Calm Male Lead, Strong Female Lead, Friendship, Smart Female Lead, Soulmates",
           "Rank": "#15", "Rating": "9.0"},
          {"Name": "Alchemy of Souls Season 2", "Year of release": "2022", "Aired Date": "Dec 10, 2022 - Jan  8, 2023",
           "Aired On": " Saturday, Sunday", "Number of Episode": "10", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 21 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Jang Uk returns from death, and three years later, the story of the mages unfolds anew. Jang Uk becomes a hunter of the soul-shifters when a young woman, a prisoner in her own home, seeks his help to reclaim her freedom.",
           "Cast": "Lee Jae Wook, Go Youn Jung, Hwang Min Hyun, Shin Seung Ho, Yoo  Joon Sang, Oh Na Ra",
           "Genre": "Action,  Historical,  Romance,  Fantasy ",
           "Tags": "Magical Power, Strong Male Lead, Marriage Of Convenience, Fantasy World, Smart Male Lead, Birth Secret, Nice Male Lead, Transmigration, Supernatural, Antihero Male Lead",
           "Rank": "#16", "Rating": "9.0"},
          {"Name": "Extraordinary Attorney Woo", "Year of release": "2022", "Aired Date": "Jun 29, 2022 - Aug 18, 2022",
           "Aired On": " Wednesday, Thursday", "Number of Episode": "16", "Network": "ENA,  Netflix ",
           "Duration": "1 hr. 17 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Diagnosed with autism spectrum disorder, 27-year-old Woo Young Woo graduated at the top of her class from the prestigious Seoul National University for both college and law school due to her high IQ of 164, impressive memory, and creative thought process. Working as a lawyer, she finds herself struggling when it comes to social interactions.",
           "Cast": "Park Eun Bin, Kang Tae Oh, Kang Ki Young, Jeon Bae Soo, Baek Ji Won, Jin Kyung",
           "Genre": "Law,  Romance,  Life,  Drama ",
           "Tags": "Autistic Female Lead, Autism, Attorney Female Lead, Smart Female Lead, Workplace Setting, Nice Male Lead, Father-Daughter Relationship, Courtroom Setting, Single Mother/Father Supporting Character, Slow Burn Romance",
           "Rank": "#17", "Rating": "8.9"},
          {"Name": "Vincenzo", "Year of release": "2021", "Aired Date": "Feb 20, 2021 - May  2, 2021",
           "Aired On": " Saturday, Sunday", "Number of Episode": "20", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 25 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "At the age of eight, Park Joo Hyeong left for Italy after being adopted. Now an adult, he is known as Vincenzo Cassano and employed by a Mafia family as a consigliere. Due to warring Mafia factions, he flies to South Korea where he gets involved with lawyer Hong Cha Young. She is the type of attorney who will do anything to win a case. Now back in his motherland, he gives an unrivalled conglomerate a taste of his own medicineâ€”with a side of his own version of justice.",
           "Cast": "Song Joong Ki, Jeon Yeo Been, Ok Taec Yeon, Kim Yeo Jin, Jo Han Chul, Kwak Dong Yeon",
           "Genre": "Comedy,  Law,  Crime,  Drama ",
           "Tags": "Mafia, Revenge, Slight Romance, Eccentric Female Lead, Smart Male Lead, Injustice, Black Comedy, Corrupt Legal System, Badass Male Lead, Skilled Killer",
           "Rank": "#18", "Rating": "8.9"},
          {"Name": "Navillera", "Year of release": "2021", "Aired Date": "Mar 22, 2021 - Apr 27, 2021",
           "Aired On": " Monday, Tuesday", "Number of Episode": "12", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 5 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "A 70-year-old with a dream and a 23-year-old with a gift lift each other out of harsh realities and rise to the challenge of becoming ballerinos.",
           "Cast": "Park In Hwan, Song Kang, Na Moon Hee, Hong Seung Hee, Kim Tae Hoon, Yoon  Ji Hye",
           "Genre": "Life,  Drama ",
           "Tags": "Ballet, Life Lesson, Unusual Friendship, Adapted From A Webtoon, Second Chance, Father-Son Relationship, Character Development, Grandpa-Granddaughter Relationship, Bromance, Kind Male Lead",
           "Rank": "#19", "Rating": "8.9"},
          {"Name": "It's Okay to Not Be Okay", "Year of release": "2020", "Aired Date": "Jun 20, 2020 - Aug  9, 2020",
           "Aired On": " Saturday, Sunday", "Number of Episode": "16", "Network": "Netflix,  tvN ",
           "Duration": "1 hr. 15 min.", "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Moon Gang Tae is a community health worker at a psychiatric ward who was blessed with everything including a great body, smarts, ability to sympathize with others, patience, ability to react quickly, stamina, and more. Meanwhile, Ko Moon Young is a popular writer of childrenâ€™s literature who, due to suffering from an antisocial personality disorder, seems extremely selfish, arrogant, and rude.",
           "Cast": "Kim Soo Hyun, Seo Yea Ji, Oh Jung Se, Park Gyu Young, Jang Young Nam, Kim Chang Wan",
           "Genre": "Psychological,  Comedy,  Romance,  Drama ",
           "Tags": "Possessive Female Lead, Independent Female Lead, Successful Female Lead, Melodrama, Healing, Selfless Male Lead, Badass Female Lead, Psychiatry, Childhood Connection, Trauma",
           "Rank": "#20", "Rating": "8.9"},
          {"Name": "Signal", "Year of release": "2016", "Aired Date": "Jan 22, 2016 - Mar 12, 2016",
           "Aired On": " Friday, Saturday", "Number of Episode": "16", "Network": "tvN ", "Duration": "1 hr. 15 min.",
           "Content Rating": "15+ - Teens 15 or older ",
           "Synopsis": "Fifteen years ago, a young girl was kidnapped on the way from school, and Park Hae Yeong, who was an elementary school student at that time, witnessed the crime. A few days later, the girl was found dead, and the police were not able to find the culprit. As time went by, Hae Yeong started distrusting the police. ",
           "Cast": "Lee Je Hoon, Kim Hye Soo, Jo Jin Woong, Kim Won Hae, Lee Yoo Joon, Jang Hyun Sung",
           "Genre": "Thriller,  Mystery,  Sci-Fi ",
           "Tags": "Different Timelines, Butterfly Effect, Murder, Hwaseong Serial Murders, Suspense, Investigation, Death, Tragic Past, Corruption, Time Altering",
           "Rank": "#21", "Rating": "8.9"},
          {"Name": "The Glory", "Year of release": "2022", "Aired Date": "Dec 30, 2022", "Aired On": " Friday",
           "Number of Episode": "8", "Network": "Netflix ", "Duration": "50 min.",
           "Content Rating": "18+ Restricted (violence & profanity) ",
           "Synopsis": "A high school student dreams of becoming an architect. However, she had to drop out of school after suffering from brutal school violence. Years later, the perpetrator gets married and has a kid. Once the kid is in elementary school, the former victim becomes her homeroom teacher and starts her thorough revenge towards the perpetrators and bystanders of her bullying days.",
           "Cast": "Song Hye Kyo, Lee Do Hyun, Im Ji Yeon, Yeom Hye Ran, Park Sung Hoon, Jung Sung Il",
           "Genre": "Thriller,  Drama,  Melodrama ",
           "Tags": "Revenge, School Bullying, School Violence, Strong Female Lead, Social Issues, Sexual Content, Antiheroine Female Lead, Doctor Male Lead, Teacher Female Lead, Time Skip",
           "Rank": "#22", "Rating": "8.9"}

       ]
